// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package th.ac.sut.pizza.domain;

import org.springframework.beans.factory.annotation.Configurable;
import th.ac.sut.pizza.domain.Base;

privileged aspect Base_Roo_Configurable {
    
    declare @type: Base: @Configurable;
    
}
